name: Django CD
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: awsbreathpanda #${{ github.actor }}
          password: Libin1982 #${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: awsbreathpanda/mysite/mysite
          tag_with_ref: true
